### ISSUE TITLE
能否修改成一人每天固定人品

### ISSUE THREAD

**Issue by rainyorange** [SkyDynamic/nonebot_plugin_jrrp#1]
rt

**Comment by rainyorange** [comment]
呃好像是j开头的语句会随机发送人品 所以造成了不是固定的假象

**Comment by SkyDynamic** [comment]
> 呃好像是j开头的语句会随机发送人品 所以造成了不是固定的假象

这个是每天固定滴，因为不是random函数的，这个算法是通过传递参数然后获取今天的年月日进行哈希运算然后保留0-100的，所以每天是会固定的，不用担心不是固定

**Comment by kotoritan** [comment]
> > 呃好像是j开头的语句会随机发送人品 所以造成了不是固定的假象
> 
> 这个是每天固定滴，因为不是random函数的，这个算法是通过传递参数然后获取今天的年月日进行哈希运算然后保留0-100的，所以每天是会固定的，不用担心不是固定

目前是单独一个命令固定一个人品值，另输入一个就重新随机了...比如jrrp固定是50，jrrp123固定是80。想请教下大佬怎么改成只输入“jrrp”触发呢

**Comment by SkyDynamic** [comment]
> > > 呃好像是j开头的语句会随机发送人品 所以造成了不是固定的假象
> > 
> > 
> > 这个是每天固定滴，因为不是random函数的，这个算法是通过传递参数然后获取今天的年月日进行哈希运算然后保留0-100的，所以每天是会固定的，不用担心不是固定
> 
> 目前是单独一个命令固定一个人品值，另输入一个就重新随机了...比如jrrp固定是50，jrrp123固定是80。想请教下大佬怎么改成只输入“jrrp”触发呢

是这样的，直接输入”jrrp“或者”j“指令是传递你的QQ号作为计算参数，比如说你的QQ号是123，你输入了jrrp，那么传递过去的就是str之后的123，计算出来的人品值是80；如果你在后面加上了123（jrrp后参数可以不需要空格）：”jrrp123“，那么因为是跟你的QQ号相同所以人品值就是80，”jrrp“或”j“指令之后输入任意字符就会传递除了指令之外的所有字符作为运算值，比如我输入的是：”jrrpabcjrrp“或者"jabcj"，那么它就会忽略"jrrp"和"j"（指令不是之后的），它传递的参数就分别是："abcjrrp"和"abcj"
